version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: >
                bash -c "python manage.py makemigrations &&
                            python manage.py migrate &&
                            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - db
            - redis
    celery:
        build: .
        command: celery -A project_template worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        command: celery -A project_template beat -l INFO
        volumes:
            - .:/usr/src/app
        depends_on:
            - django
            - redis
    db:
        image: postgres
        container_name: db
        environment:
            - POSTGRES_DB=database
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=p@ss123
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"
        
volumes:
    pgdata: